version: "3.1"

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  back-tier:

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    # volumes:
    #   - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=20d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always

  grafana:
    image: grafana/grafana:5.1.3
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - back-tier
    volumes:
      - ./grafana:/var/lib/grafana
    env_file:
      - ./grafana/config.monitoring
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.20.0
    depends_on:
      - prometheus
    ports:
      - 9093:9093
    networks:
      - back-tier
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    restart: always
